DROP TABLE IF EXISTS links;

DROP TABLE IF EXISTS fnames;

DROP TABLE IF EXISTS fids;

DROP TABLE IF EXISTS casts;

DROP TABLE IF EXISTS reactions;

DROP TABLE IF EXISTS signers;

DROP TABLE IF EXISTS verifications;

DROP TABLE IF EXISTS userData;

DROP TABLE IF EXISTS messages;
